### PR TITLE
Implement EncryptedKey RetrievalMethod support

### PR DESCRIPTION
**Pull request by distol**
Implemented support for [EncryptedKey RetrievalMethod] (https://www.w3.org/TR/2002/REC-xmlenc-core-20021210/Overview.html#sec-eg-EncryptedKey).

Example
```xml
  <saml2:EncryptedAssertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
    <xenc:EncryptedData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Id="_073b6815e847fee92645b4555c09cf6c" Type="http://www.w3.org/2001/04/xmlenc#Element">
      <xenc:EncryptionMethod xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Algorithm="http://www.w3.org/2001/04/xmlenc#aes256-cbc"/>
      <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:RetrievalMethod Type="http://www.w3.org/2001/04/xmlenc#EncryptedKey" URI="#_8086c3e85abfdda1e308f3b255abe5dc"/>
      </ds:KeyInfo>
      <xenc:CipherData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#">
        <xenc:CipherValue>xxx</xenc:CipherValue>
      </xenc:CipherData>
    </xenc:EncryptedData>
    <xenc:EncryptedKey xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Id="_8086c3e85abfdda1e308f3b255abe5dc">
      <xenc:EncryptionMethod xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p">
        <ds:DigestMethod xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
      </xenc:EncryptionMethod>
      <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:X509Data>
          <ds:X509Certificate>xxxx</ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
      <xenc:CipherData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#">
        <xenc:CipherValue>xxx</xenc:CipherValue>
      </xenc:CipherData>
    </xenc:EncryptedKey>
  </saml2:EncryptedAssertion>
```

### CODE REVIEW

**Comment by mchaisse** [comment]
I have a client using this same different format. @pitbulk can you please consider this PR? :)

**Comment by distol** [comment]
Okta uses this format when assertions encryption is enabled. This PR is fully backward compatible and should not break anything!

**Comment by pitbulk** [comment]
Can you provide specific unit test for that?
I think we can merge this change after that.

**Comment by mchaisse** [comment]
@distol do you have any example we can use for the tests? If not I can probably find some. If you don't have time, no problem, I can probably open another PR with the proper tests :)

**Comment by distol** [comment]
Give me a couple of days and I'll do it.

**Comment by Seraff** [comment]
@pitbulk, I added a test for RetrievalMethod support. It is similar to "it is possible to decrypt the assertion if private key", but uses another XML response. Is it ok?

**Comment by pitbulk** [comment]
Thanks for the contribution guys, I will review if there is any security issue related to this change and I will share with the rest to the team. 

I hope to merge it as soon as possible.

**Pull request merged**
