### PR TITLE
Not raise an error when there are multiple signature nodes

### PR DESCRIPTION
**Pull request by soartec-lab**
Thanks for providing this wonderful library. I found one problem while using this library. This wasn't compliant with the SAML 2.0 spec so I fixed it. Please confirm.

## Expected
Allow the presence of multiple signatures.

SAML 2.0 spec allows for this. 
In fact, the Java library `java-saml` you provide allows multiple signatures.

See: https://github.com/onelogin/java-saml/blob/e69b53b1befbd3065d958d325d44fbc9bc74a56d/core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java#L308-L310

## Now
not allow the presence of multiple signatures.

commit by https://github.com/perryism/ruby-saml/commit/059abe4cfde3e4afbc703d6eadba7831fd6ea343

### CODE REVIEW

**Comment by pitbulk** [comment]
The java-saml library checks for the presence of no more than 2 Signatures here:
https://github.com/onelogin/java-saml/blob/e69b53b1befbd3065d958d325d44fbc9bc74a56d/core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java#L918

What scenario are you trying to cover?

SAML specs allow multiple Assertions, but in practice, IdPs do not send more than 1.

Preventing no more than 2 Signatures and verify that the signed elements belong a Response or Assertion helps to prevent Signature wrapping attacks and other abuses.

Can you provide more info about why you need to remove this restriction?

**Comment by soartec-lab** [comment]
@pitbulk 
Thank you for reply!

I'm sorry. Java library java-saml also didn't allow the existence of multiple signatures.

> What scenario are you trying to cover?

Yes, there are scenarios that require two signatures.
This is because the SAML specification allows multiple assertions, so some service providers working together in a real business need to sign the entire response and the assertions. For example, Slack can make such settings.

Also, as another scenario, when changing the signing certificate as an IDP, there is a case where you want to publish the new certificate in parallel with the old certificate.

**Comment by pitbulk** [comment]
This toolkit only allows 1 assertion per message.

And validating the Signature of the Request with 1 cert and the other of the assertion with other cert makes no sense to me.

I'm curious, can you share the slack doc link?

**Comment by soartec-lab** [comment]
@pitbulk 

Details are not described in the help center, but you can check it by actually visiting the setting screen.

https://slack.com/help/articles/203772216-SAML-single-sign-on

It can be selected as an item in the following `Choose how the SAML response from your IDP is signed.`.

> 9. Next to Advanced Options, click Expand. Choose how the SAML response from your IDP is signed. If you need an end-to-end encryption key, check the box next to Sign AuthnRequest to show the certificate.

**Comment by soartec-lab** [comment]
I found the target page in the slack integration document on okta, so I will share it as an alternative.

https://saml-doc.okta.com/SAML_Docs/How-to-Configure-SAML-2.0-for-Slack.html

In the reference image of '6. Under Advanced Options, use the default value for the Service Provider Issuer.', You can specify the option for signing the saml response.

**Comment by pitbulk** [comment]
In that image I see you can enable/disable the Signatures on the AuthNRequest

as well as decide if require
- Signed Response.
- Signed Assertion.
- Signed Response and Assertion.

That is totally ok and the ruby-saml toolkit support it.

What is checked [here](https://github.com/onelogin/ruby-saml/blob/1.12.0-dev/lib/onelogin/ruby-saml/response.rb#L838) is that the Assertion only contains 1 Signature and not more than 1

Here you see a test validating a Signed SAMLResponse with a signed assertion:
https://github.com/onelogin/ruby-saml/blob/9f710c5028b069bfab4b9e2b66891e0549765af5/test/xml_security_test.rb#L344

**Comment by soartec-lab** [comment]
@pitbulk 

Oh really. In other words, it also supports the presence of signatures in responses and assertions, as shown below, right?

```
<?xml version="1.0" encoding="UTF-8"?>
<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_495be3639c58a908c210891cd6a20d9d568c57212c" Version="2.0" IssueInstant="2018-12-12T12:17:50Z" Destination="http://my-sp-url.com/saml/default-sp" InResponseTo="_0ded736b3fb9339e1f5922c7ec2e5746be75aa2734">
    <saml:Issuer>http://my-idp-url.com/saml2</saml:Issuer>
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:SignedInfo>
            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
            <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
            <ds:Reference URI="#_495be3639c58a908c210891cd6a20d9d568c57212c">
                <ds:Transforms>
                    <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                    <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                </ds:Transforms>
                <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
                <ds:DigestValue><Key here></ds:DigestValue>
            </ds:Reference>
        </ds:SignedInfo>
        <ds:SignatureValue><Key here></ds:SignatureValue>
        <ds:KeyInfo>
            <ds:X509Data>
                <ds:X509Certificate>My Key</ds:X509Certificate>
            </ds:X509Data>
        </ds:KeyInfo>
    </ds:Signature>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </samlp:Status>
    <saml:Assertion xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ID="_865db5e11802e17eed94a0f62c7dd128458e3b93c4" Version="2.0" IssueInstant="2018-12-12T12:17:50Z">
        <saml:Issuer>http://my-idp-url.com/saml2</saml:Issuer>
        <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
            <ds:SignedInfo>
                <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
                <ds:Reference URI="#_865db5e11802e17eed94a0f62c7dd128458e3b93c4">
                    <ds:Transforms>
                        <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                        <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                    </ds:Transforms>
                    <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
                    <ds:DigestValue>Z1hqzHHQYtiEc/pIu4u+U0NzDEcjIcfBO6+tagO50wY=</ds:DigestValue>
                </ds:Reference>
            </ds:SignedInfo>
            <ds:SignatureValue>MJkIwHc+<Key here></ds:SignatureValue>
            <ds:KeyInfo>
                <ds:X509Data>
                    <ds:X509Certificate>My Key</ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
        </ds:Signature>
        <saml:Subject>
            <saml:NameID SPNameQualifier="http://my-sp-url.com/module.php/saml/sp/metadata.php/default-sp" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient">_86a05110a6cd9415db1f6451e090de5a1f565e61c3</saml:NameID>
            <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <saml:SubjectConfirmationData NotOnOrAfter="2018-12-12T12:22:50Z" Recipient="http://my-sp-url.com/module.php/saml/sp/saml2/default-sp" InResponseTo="_0ded736b3fb9339e1f5922c7ec2e5746be75aa2734" />
            </saml:SubjectConfirmation>
        </saml:Subject>
        <saml:Conditions NotBefore="2018-12-12T12:17:20Z" NotOnOrAfter="2018-12-12T12:22:50Z">
            <saml:AudienceRestriction>
                <saml:Audience>http://my-sp-url.com/saml/sp/</saml:Audience>
            </saml:AudienceRestriction>
        </saml:Conditions>
        <saml:AuthnStatement AuthnInstant="2018-12-12T12:15:54Z" SessionNotOnOrAfter="2018-12-12T20:15:54Z" SessionIndex="_8ba981181bba69f5a49ac2a871829b7df3b76051cb">
            <saml:AuthnContext>
                <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml:AuthnContextClassRef>
            </saml:AuthnContext>
        </saml:AuthnStatement>
        <saml:AttributeStatement>
            <saml:Attribute Name="USER NUMBER" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
                <saml:AttributeValue xsi:type="xs:string">test-user-123</saml:AttributeValue>
            </saml:Attribute>
        </saml:AttributeStatement>
    </saml:Assertion>
</samlp:Response>

```

**Comment by pitbulk** [comment]
Yes.

I only check that there is only 1 Signature per expected signed node as extra protection for signature wrapping attacks.

**Comment by soartec-lab** [comment]
Roger that. I understand that I only allow one signature per assertion here. Thank you for teaching me.
It's been the best time.
This PR will be closed.

**Pull request closed without merging**
