### PR TITLE
Base project updates

### PR DESCRIPTION
**Pull request by phlipper**
I am currently working on a fork of this repo for a client. I have made some key updates which I will work on contributing back _(if you're interested)_ in future PRs. 

This initial work updates some core assumptions about the project:

* Remove support for Ruby < 2.0 - 1.8 is EOL for some time, and 1.9 is EOL this month
* Update dependencies _(both development and runtime)_ to latest versions
* Add color and coverage information to test runs
* Update CI jobs

/cc @Lordnibbler

### CODE REVIEW

**Comment by pitbulk** [comment]
@phlipper  Nice, we are also cleaning the repo. We will release the branch soon with a lot of changes and we will review your PRs.

**Comment by Lordnibbler** [comment]
@phlipper it's going to be tricky for us to merge this as it drops support for 1.8.7, which I know some of our internal tools use, as well as some of the contributors to this gem.

Would you reconsider your decision to drop 1.8.7 and 1.9.x support from this PR?

**Comment by phlipper** [comment]
@Lordnibbler I know this PR is a long shot, but...

> Would you reconsider your decision to drop 1.8.7 and 1.9.x support from this PR?

Ruby 1.8 has been EOL for quite some time now, and it is a security liability to keep it running. Ruby 1.9 will be EOL as of 2015-02-23. Per Ruby core:

> We highly recommend that you upgrade to Ruby 2.1 or 2.0.0 as soon as possible.

Continuing support for Ruby 1.x will also significantly hold back future improvements _(of which I am currently working on several)_. 

I understand that there are some folks who are unfortunately still running 1.8, and they should be able to stick with v0.9.x _(or whatever version prior to officially dropping Ruby 1.x support)_, but IMO, continuing to support 1.x going forward is a bad idea. 

That said, I know this is your project and your call, and I understand that we may have to just end up maintaining our own library. My hope was simply that others could benefit from some ongoing improvements.

Thanks for the time and consideration, and for maintaining this library.

**Comment by Lordnibbler** [comment]
@phlipper We're still discussing this internally, haven't forgotten :smiley:

**Comment by phlipper** [comment]
@Lordnibbler thanks for the update :)

**Comment by Lordnibbler** [comment]
@phlipper stealing a couple commits from this PR in the interim.  Keep you posted!

**Pull request closed without merging**
