### PR TITLE
Use different XPath for xenc:EncryptedKey

### LINKED ISSUE #312: decrypting encrypted assertions in ruby-saml is broken
for responses that look like:

```xml
<saml2:EncryptedAssertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
    <xenc:EncryptedData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Id="_c49ba4078e1f4e7c890eec5c488cf4d5" Type="http://www.w3.org/2001/04/xmlenc#Element">
      <xenc:EncryptionMethod xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/>
      <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:RetrievalMethod Type="http://www.w3.org/2001/04/xmlenc#EncryptedKey" URI="#_b8fba8d1aab229c5b42f0fb1a78e239d"/>
      </ds:KeyInfo>
...
```

Ruby saml tries (https://github.com/onelogin/ruby-saml/blob/45665bac6f33f656273517e7107122dbe81cd252/lib/onelogin/ruby-saml/utils.rb#L127) to access an XPath inside `ds:KeyInfo` that doesn't exist, which explodes. Note that decrypting this response online with the tools you make at samltool.com work perfectly well.

### PR DESCRIPTION
**Pull request by vincentwoo**
Resolves #312, please comment there for main discussion.

### CODE REVIEW

**Comment by vignesh-vs-in** [comment]
Stumbled upon the same issue, ended up with fixing it in exactly the same way. Awaiting the PR to be merged. Thanks

**Comment by pitbulk** [comment]
PR #297 is related to this issue, have you checked it?

**Comment by vincentwoo** [comment]
That seems relevant. Are you reviewing #297? When can we expect a fix?

**Comment by pitbulk** [comment]
Does the PR of #297 solve your issue?

**Comment by vincentwoo** [comment]
The responses I am receiving use retrievalmethod as well, so it should.

**Comment by pitbulk** [comment]
Please test the other solution (#297) and if fix your issue I will merge it.

Thanks

**Comment by pitbulk** [comment]
Fixed that with PR #297

**Pull request closed without merging**
