### PR TITLE
Adding supported for Encrypted SAML 

### PR DESCRIPTION
**Pull request by ksinkar**
These changes are for adding support for **encrypted** SAML messages. [xmlenc] (https://github.com/digidentity/xmlenc) from has been used for encryption and decryption. All existing tests for ruby-saml are passing. I had to upgrade the timecop gem though, for the tests to pass on my local machine. Unfortunately these are failing on Travis CI for REE and 1.8.x 

@buffym @googya, could you please check and let me know if this works for your cases of Ping Federate and Encryption otherwise.

#9 #193 #186 #172

### CODE REVIEW

**Comment by pitbulk** [comment]
Thanks @ksinkar, we will review all this code and integrate it in the ruby-saml gem this functionality for sure.

**Comment by ksinkar** [comment]
@pitbulk, I had a look at the decrypt branch in which you are developing the decrypt functionality. It  seems that branch is only able to handle signing and checking of digest methods for encrypted assertions. I don't see any code for decrypting the encrypted assertions. 

Please correct me if I am wrong in the above inference.

I am eager to  get the decryption functionality into this gem. I suggest that you merge my changes into master or the decrypt branch as you see fit. As for the failing tests, it is  dependency problem of nokogiri which I have tried to solve by updating the xmlenc gemspec as well, but not yet been able to solve it. If you have any ideas please let me know and I shall solve them pronto.

**Comment by pitbulk** [comment]
@ksinkar  Here is the code to decrypt assertions:
https://github.com/onelogin/ruby-saml/blob/decrypt/lib/onelogin/ruby-saml/response.rb#L258

**Comment by pitbulk** [comment]
Replaced by #241. Right now we avoid the use of xmlenc.

**Pull request closed without merging**
