### PR TITLE
Signature algorithm would not be changed by signature method. Algorithm ...

### PR DESCRIPTION
**Pull request by polika78**
Signature algorithm would not be changed by signature method. Algorithm method's argument was not REXML:Element, so fixed it.

### CODE REVIEW

**Comment by Lordnibbler** [comment]
@pitbulk @luisvm  thoughts on this? seems sane to me :+1:

**Comment by pitbulk** [comment]
The algorithm method accepts  REXML::Element or an string that represent the signature algorithm like RSA_SHA1.  I don't see why is better pass the signed_method_element instead the signature_method parameter directly.

**Comment by polika78** [comment]
The algorithm method is parsing the signature method as integer number (ex. sha256 -> 256) when the signature method is only REXML::Element. The signature method usually includes prefix like 'sha'. If this method accept both type Element or string for the signature method, I think that algorithm method should be fixed for parsing properly.

**Comment by pitbulk** [comment]
Fixed at https://github.com/onelogin/ruby-saml/commit/e96becf57a725dd090aefff783c9fd37be900a47

**Pull request closed without merging**
