### PR TITLE
Default sso_target_url and slo_target_url to HTTP-Redirect binding

### PR DESCRIPTION
**Pull request by kahlouie**
## Status
**READY**

## Migrations
NO

## Description
This solves the issue #279 of multiple `SingleSignOnService` and `SingleLogoutService` elements in IdP metadata files. The correct behavior should prefer the element with the binding of `urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect`.

## Related PRs
None

## Todos
- [x] Tests
- [x] Documentation

## Deploy Notes
N/a

## Steps to Test or Reproduce
This is tested in [test/idp_metadata_parser_test.rb](https://github.com/onelogin/ruby-saml/blob/master/test/idp_metadata_parser_test.rb)

1. bundle exec rake test TEST=test/idp_metadata_parser_test.rb

## Impacted Areas in Application
List general components of the application that this PR will affect:

* This will affect the IdP metadata parser.

### CODE REVIEW

**Comment by kahlouie** [comment]
@pitbulk ready for review! Thanks!

**Comment by raulb** [comment]
Hi @jimcamut @luisvm @meyerworks @naveedehmad @pitbulk.

Currently in Heroku we're using our [own fork](https://github.com/heroku/ruby-saml) of this gem that fixes the issue identified by @kara, and we'd love to point out our gem to this upstream repository.

We also believe the implementation of this PR would be beneficial for the rest of the community.

Is there anything missing here, or do you all think we could merge this in? Please, let us know.

Thanks,
Raúl

**Comment by pitbulk** [comment]
This should be fixed with this commit:
https://github.com/onelogin/ruby-saml/commit/2e60902adf7748cdb323577051dd915cac2f1a30

**Comment by raulb** [comment]
@pitbulk thanks

**Pull request closed without merging**
