### PR TITLE
Use secure random and encapsulate uuid creation

### PR DESCRIPTION
**Pull request by subfusc**
Rebase of and patched for backwards compatability for #206.

### CODE REVIEW

**Comment by pitbulk** [comment]
Thanks for contribute, I will review it and merge it as soon as possible ;)

**Comment by subfusc** [comment]
Is there an ETA for this? As described in the linked topic, this is producing actual errors when using the library.

**Comment by ilikepi** [comment]
A big :+1: to this.  We ran into an issue last night due to the way the uuid gem determines where to store its state file by default.

**Comment by subfusc** [comment]
uuid is only included as a dependency if your ruby version is less than 1.9. At least that is the intent.

**Pull request merged**
