### PR TITLE
Intermediate certificate support

### PR DESCRIPTION
**Pull request by alex-wood**
Adds support for intermediate certificates and corresponding test cases.

### CODE REVIEW

**Comment by pitbulk** [comment]
Why Intermediate certificate support is required? Can you explain?

**Comment by alex-wood** [comment]
For certain certificates, there’s no path for verifying the trust chain unless one provides intermediate certificates in the metadata response. My changes follow the [spec for XML signatures](https://www.w3.org/TR/xmldsig-core/#sec-X509Data), which describes how intermediate signatures are included.

**Comment by pitbulk** [comment]
In the toolkit, the Signature verification is done in 2 steps:
* Check that the signature value is actually corresponding to the content it protects
* Check that the signature was made by someone trusted by the verifier (the certificate matches the IdP certificate registered in the settings.

At the toolkit we don't verify that the certificate itself is valid, so I don't think that "intermediate certificate" stuff is required...

Can you provide a SAMLResponse not able to be validated?

**Comment by alex-wood** [comment]
To be clear, the issue is about the IdP not accepting our metadata file because the trust chain for the service provider certificate is not there.

**Comment by pitbulk** [comment]
I think this solves such an specific scenario and I dislike be adding new settings parameters for that.

In order to solve your case, I think you better extend the metadata class and modify the generate method to accept intermediate certs.

**Pull request closed without merging**
