### PR TITLE
Allow requirement of single files

### PR DESCRIPTION
**Pull request by rafaelgonzalez**
This is to reflect the [advertised behaviour in the README](https://github.com/onelogin/ruby-saml/tree/3264e2f97629fc8e459f64eb883c4b850abd8e92#getting-started).

You can manually test requirements of each file in `irb` (exiting `irb` between each) with:

- `require_relative 'lib/onelogin/ruby-saml/authrequest'`
- `require_relative 'lib/onelogin/ruby-saml/logoutrequest'`
- `require_relative 'lib/onelogin/ruby-saml/logoutresponse'`
- `require_relative 'lib/onelogin/ruby-saml/settings'`
- `require_relative 'lib/onelogin/ruby-saml/slo_logoutrequest'`
- `require_relative 'lib/onelogin/ruby-saml/slo_logoutresponse'`

### CODE REVIEW

**Comment by pitbulk** [comment]
:+1:

**Comment by pitbulk** [comment]
@luisvm , @Lordnibbler what do you think?

**Comment by cgthornt** [comment]
:+1:

**Comment by luisvm** [comment]
:+1:

**Comment by Lordnibbler** [comment]
:+1:

**Comment by Lordnibbler** [comment]
thank you @rafaelgonzalez !

**Comment by rafaelgonzalez** [comment]
Cheers everyone

**Comment by pitbulk** [comment]
The file onelogin.rb is unnecessary since we don't use any
require 'onelogin' anywhere.

I noticed that in ruby-saml-example we never used 
```
require 'onelogin/ruby-saml'
```
with the gem installed, it imports the lib/ruby-saml.rb  so the library is available.


After read the [REQUIRING CODE section of rubygem](http://guides.rubygems.org/rubygems-basics/#requiring-code) I saw that is common to set in the lib path a file with the name of the library, so I will replace lib/onelogin.rb by lib/ruby-saml.rb .That will maintain ruby-saml-example compatibility.

@Lordnibbler, are you agree?

**Pull request merged**
