### PR TITLE
Handle valid but uncommon dsig block with no URI in the reference

### PR DESCRIPTION
**Pull request by knightlabs**
Encountered a situation in which the ds:Reference block in a message signature was empty; published as kl-ruby-saml-0.0.2 if anyone wants to test that fork from 1.0.0; example response:

    
    <?xml version="1.0"?>
    <samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="pfxd594347d-495f-b8d1-0ee2-41cfda14dd35" Version="2.0" IssueInstant="2015-01-02T22:48:48Z" Destination="http://localhost:9001/v1/users/authorize/saml" Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified" InResponseTo="_ed915a40-74fb-0132-5b16-48e0eb14a1c7">
      <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">http://example.com</Issuer><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
      <ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
        <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
      <ds:Reference URI=""><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><ds:DigestValue>jCgeXCPDFlwjTgqgPp0mU2Tqw9g=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>Dfupr18wR+rDagtCPEfQlSGHzw4NdfPHZ4HszFe1JPCJXjfbyEM1fg+jzgGbMMt6XzgCXcKJM7E/CPSTDkvMe3DUJlHu4DhuDOAz/DsyoBwWuV+Rf3WiNcF4XCc9wBQzvn/atD7zW6xwO7N/hkAZJqfvJddnpMMHKGXqG/ZHZAw=</ds:SignatureValue>
    <ds:KeyInfo><ds:X509Data><ds:X509Certificate>MIICqDCCAhGgAwIBAgIBADANBgkqhkiG9w0BAQ0FADBxMQswCQYDVQQGEwJ1czETMBEGA1UECAwKV2FzaGluZ3RvbjEiMCAGA1UECgwZRmxhdCBXb3JsZCBLbm93bGVkZ2UsIEluYzEcMBoGA1UEAwwTbGVhcm4uZmxhdHdvcmxkLmNvbTELMAkGA1UEBwwCREMwHhcNMTUwNzA4MDk1OTAzWhcNMjUwNzA1MDk1OTAzWjBxMQswCQYDVQQGEwJ1czETMBEGA1UECAwKV2FzaGluZ3RvbjEiMCAGA1UECgwZRmxhdCBXb3JsZCBLbm93bGVkZ2UsIEluYzEcMBoGA1UEAwwTbGVhcm4uZmxhdHdvcmxkLmNvbTELMAkGA1UEBwwCREMwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAMPDwsl5o6x2QouNi1/E7IUqRYj2YocJRFsuEGTevyU+2aFCaBNV/tt6sAbM9WSutLuqjE/hfbnlEcZ03+gn0CoLl6YmwbKKeRpkIzeVhoyJ1YYMQEAVhLrdy8Powu8UCZ0PbAz+n9dkiRzM5pCCO77+gycFTBFKHAA9qIpUZZkPAgMBAAGjUDBOMB0GA1UdDgQWBBQHU58iuGxFlZurBUJwolalJr+FRzAfBgNVHSMEGDAWgBQHU58iuGxFlZurBUJwolalJr+FRzAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBDQUAA4GBAC6iHfMmd+hMSRzfkosi3C+wvqHCLEUsg3HFpkZm5jxmTDlF5qO+Bt0n0xmfoqWBzBMlNC8TsGrafhJ3zu8GNF0Leo11rfc1GMGBvr5HoZ3WAAymnBEDAAosxN6WZRmj1xaga13+6pWfGB++2nPwcZWP/8dkPcRogevV0x0p5686</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature>
      <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
      </samlp:Status>

      <Assertion xmlns="urn:oasis:names:tc:SAML:2.0:assertion" ID="_700ac320-74ff-0132-5b14-48e0eb14a1c7" IssueInstant="2015-01-02T22:48:48Z" Version="2.0">
        <Issuer>http://example.com</Issuer>
        <Subject>
          <NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">saml@user.com</NameID>
          <SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
            <SubjectConfirmationData InResponseTo="_ed915a40-74fb-0132-5b16-48e0eb14a1c7" NotOnOrAfter="2038-01-02T22:51:48Z" Recipient="http://localhost:9001/v1/users/authorize/saml"/>
          </SubjectConfirmation>
        </Subject>
        <Conditions NotBefore="2015-01-02T22:48:43Z" NotOnOrAfter="2038-01-02T23:48:48Z">
          <AudienceRestriction>
            <Audience>http://localhost:9001/</Audience>
            <Audience>flat_world</Audience>
          </AudienceRestriction>
        </Conditions>
        <AttributeStatement>
          <Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress">
            <AttributeValue>saml@user.com</AttributeValue>
          </Attribute>
        </AttributeStatement>
        <AuthnStatement AuthnInstant="2015-01-02T22:48:48Z" SessionIndex="_700ac320-74ff-0132-5b14-48e0eb14a1c7">
          <AuthnContext>
            <AuthnContextClassRef>urn:federation:authentication:windows</AuthnContextClassRef>
          </AuthnContext>
        </AuthnStatement>
      </Assertion>
    </samlp:Response>

Test case included. This is valid per the dsig spec – http://www.w3.org/TR/xmldsig-core/#sec-Same-Document.

### CODE REVIEW

**Comment by pitbulk** [comment]
@knightlabs your PR fails on travis:

1) Failure:
```
retrieve nameID and attributes from encrypted assertion#test_0003_is possible when unsigned_message_encrypted_signed_assertion [/home/travis/build/onelogin/ruby-saml/test/response_test.rb:996]
```

**Comment by pitbulk** [comment]
Found that [xmlseclibs](https://github.com/simplesamlphp/xmlseclibs/blob/master/xmlseclibs.php#L985), the PHP library used to handle SAML signatures/encryptions support the empty Reference, so you should be right.

**Comment by pitbulk** [comment]
@knightlabs found the problem. Please apply that change so I can merge the PR:

```
--- a/lib/xml_security.rb
+++ b/lib/xml_security.rb
@@ -344,7 +344,9 @@ module XMLSecurity
         {"ds"=>DSIG}
       )
 
-      sei = reference_element.attribute("URI").value[1..-1] unless reference_element.nil?
+      return nil if reference_element.nil? 
+      
+      sei = reference_element.attribute("URI").value[1..-1]
       self.signed_element_id = sei.nil? ? self.root.attribute("ID") : sei
     end
```

**Comment by knightlabs** [comment]
Thx @sixto! – was just getting around to figuring out what the issue was, but looks like everything is passing. Want me to squash these all down into a single commit?

**Comment by pitbulk** [comment]
If you are able, it will be welcome.

**Comment by pitbulk** [comment]
So can you create a simple commit and re-generate that PR?

**Comment by knightlabs** [comment]
Closed in favor of https://github.com/onelogin/ruby-saml/pull/254.

**Pull request closed without merging**
