### PR TITLE
Add more validations and refactor and improve tests.

### PR DESCRIPTION
**Pull request by pitbulk**
* Add more validations to the SAMLResponse class.
* Add more validations to the LogoutResponse class
* Add more validations to the LogoutRequest class
* Refactor and improve tests (+coverage).

### CODE REVIEW

**Comment by pitbulk** [comment]
@luisvm @Lordnibbler  Can you review that 1st commit of this PR?

**Comment by luisvm** [comment]
:+1: lgtm

**Comment by pitbulk** [comment]
@luisvm, @Lordnibbler,  can you validate this PR to be merged?

**Comment by luisvm** [comment]
:+1:

**Pull request merged**
