### PR TITLE
Entity expand prevent

### PR DESCRIPTION
**Pull request by pitbulk**
Related to #125 and #126. Security issues: XXE Attacks

### CODE REVIEW

**Comment by pitbulk** [comment]
@Lordnibbler What do you think about this PR?

**Comment by Lordnibbler** [comment]
Is there a reason for setting `REXML::Document::entity_expansion_limit = 0` multiple times in different classes? If we always want this value to be 0, why not just set `REXML::Document::entity_expansion_limit = 0` just once, since it will be defined at the class level?

**Comment by phlipper** [comment]
I agree with @Lordnibbler, otherwise LGTM

**Comment by Lordnibbler** [comment]
Needs  rebase @pitbulk

**Pull request closed without merging**
