### PR TITLE
Allow logging to be delegated to an arbitrary Logger

### PR DESCRIPTION
**Pull request by tony-spataro-rs**

### CODE REVIEW

**Comment by tony-spataro-rs** [comment]
@pitbulk - any objection to this change? It seems harmless, and allows for smoother integration with the host app's logging.

**Comment by Lordnibbler** [comment]
@tony-spataro-rs thanks for this contribution -- I'm ok with it if you could just add some information to the readme on how to use this new logging feature.

Thanks

**Comment by tony-spataro-rs** [comment]
@Lordnibbler done; :shipit: !

**Comment by tony-spataro-rs** [comment]
@Lordnibbler or @pitbulk - any chance of getting this merged before the next release?

**Comment by Lordnibbler** [comment]
thanks, unfortunately in order to merge this branch we will need to rebase it off of `master`. can you do this @tony-spataro-rs? then we can release it as part of v1.0

**Comment by stevecrozz** [comment]
@Lordnibbler I rebased these changes onto master

**Pull request merged**
